-- SMS as a distinct conversation channel.
--
-- Adds "sms" to the session_channel enum so inbound text-message conversations
-- (Twilio SMS webhook) are tracked separately from "phone" voice calls in the
-- admin board's channel badge and filter, rather than being lumped in with
-- voice. Existing rows are unaffected (their channel stays "web" or "phone").
--
-- Postgres enum values are added in place with ALTER TYPE ... ADD VALUE; we use
-- IF NOT EXISTS so the migration is idempotent. Appended after "phone" — sort
-- position doesn't matter for this enum (no ordered semantics).
--
-- Note: ALTER TYPE ... ADD VALUE cannot run inside a transaction block in
-- Postgres, and the neon-http file-migrator (drizzle-orm/neon-http/migrator)
-- fails on such files — see 0011 for the same constraint. On the live DB this
-- statement was applied out-of-band via the neon driver (autocommits), and 0014
-- was then recorded in drizzle.__drizzle_migrations. For a FRESH database, if
-- `npm run db:migrate` errors on this file, run the ALTER TYPE statement
-- directly against the DB, then insert the 0014 journal row. IF NOT EXISTS
-- keeps that safe to repeat.

ALTER TYPE "public"."session_channel" ADD VALUE IF NOT EXISTS 'sms' AFTER 'phone';
