-- Map each CRM customer to its Housecall Pro (HCP) customer, once synced.
--
-- A strict 1:1 mapping (one HCP customer id per our customer row), so a plain
-- nullable column on `customers` is simpler than a separate mapping table: no
-- extra tenant-scoped table, no join — we already load the customer row on the
-- paths that need this. NULL until the org is HCP-connected and a successful
-- find-or-create has mirrored the customer to HCP; set once and idempotent (a
-- re-sync of an already-mapped customer no-ops). Not a secret — it's HCP's
-- public resource id, so it is stored in plaintext (unlike the API key, which
-- lives encrypted on housecall_pro_connections).
--
-- Plain ADD COLUMN (nullable, no default) — no table rewrite, no enum / ALTER
-- TYPE, so it runs fine through the standard neon-http file migrator (db:migrate).
ALTER TABLE "customers" ADD COLUMN "hcp_customer_id" text;
