-- Map each service request to its Housecall Pro (HCP) job, once pushed.
--
-- A strict 1:1 mapping (one HCP job id per our service_request), so a plain
-- nullable column on `service_requests` is simpler than a separate mapping
-- table: no extra tenant-scoped table, no join — the push/reschedule/cancel
-- paths already load the request row. NULL until the org is HCP-connected and a
-- successful create-job has pushed the booking to HCP; set once and treated
-- idempotently (a re-sync of an already-pushed request UPDATEs the existing HCP
-- job rather than creating a duplicate). On cancel we delete the HCP job and the
-- column is left set for the audit trail (the HCP id is harmless once the job is
-- gone). Not a secret — it's HCP's public resource id, so it is stored in
-- plaintext (unlike the API key, which lives encrypted on
-- housecall_pro_connections). (Stage 3 of the HCP integration.)
--
-- Plain ADD COLUMN (nullable, no default) — no table rewrite, no enum / ALTER
-- TYPE, so it runs fine through the standard neon-http file migrator (db:migrate).
ALTER TABLE "service_requests" ADD COLUMN "hcp_job_id" text;
