-- Drop the stored after-hours surcharge dollar amount.
--
-- The business does NOT charge a fixed flat after-hours fee — the charge
-- depends on the actual work done, so a precomputed dollar surcharge stored on
-- the row was always wrong. We KEEP the is_after_hours flag (the window
-- detection still drives dispatch + the bot's number-free disclosure); we only
-- remove the dollar column and all the flat-fee / multiplier math behind it.
--
-- Plain ALTER TABLE DROP COLUMN — no enum / ALTER TYPE, so no in-transaction
-- hazard; runs fine through the standard neon-http file migrator.
ALTER TABLE "service_requests" DROP COLUMN "after_hours_surcharge";
