/**
 * promptfoo prompt function: assembles the real chatbot system prompt
 * (promptfoo/system-prompt.txt, regenerated by `npm run eval:promptfoo:gen`
 * from src/lib/ai/system-prompt.ts) plus the test's user query into an
 * OpenAI-style chat message array. Keeps the eval anchored to the SHIPPED
 * system prompt rather than a hand-copied snippet.
 */
const fs = require("node:fs");
const path = require("node:path");

const SYSTEM = fs.readFileSync(
  path.join(__dirname, "system-prompt.txt"),
  "utf8",
);

module.exports = async function chatPrompt({ vars }) {
  return [
    { role: "system", content: SYSTEM },
    { role: "user", content: String(vars.query ?? "") },
  ];
};
